service: getPet

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1


functions:
  omnicloud:
    handler: app.handler
    events:
      - http:
          path: /getPet
          method: get
          request:
            parameters:
              querystrings:
                tz: true
