service: PetStore

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2


functions:
  listPet:
    handler: app.handler
    events:
      - http:
          path: /pet
          method: get
          request:
            parameters:
              querystrings:
                tz: true
